# Ola 2: servicio con estado (PostgreSQL + API REST) y recursos de resiliencia.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datos
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: __REPO_URL__
    targetRevision: __REPO_RAMA__
    path: __GITOPS_RUTA__/cargas/datos
  destination:
    server: https://kubernetes.default.svc
    namespace: datos
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
